// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH2iBcT444mtjasxdgWMONF14lu9gXVtY',
    appId: '1:436153481478:android:cd39924bcf90a0ab9f8687',
    messagingSenderId: '436153481478',
    projectId: 'r01-redditx-suicide',
    storageBucket: 'r01-redditx-suicide.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQCor365hwvWKHdgTi98-R5CFMhMoEhbU',
    appId: '1:436153481478:ios:4d04d2e6257b0f0d9f8687',
    messagingSenderId: '436153481478',
    projectId: 'r01-redditx-suicide',
    storageBucket: 'r01-redditx-suicide.firebasestorage.app',
    iosBundleId: 'com.dartmouth.smerb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQCor365hwvWKHdgTi98-R5CFMhMoEhbU',
    appId: '1:436153481478:ios:4d04d2e6257b0f0d9f8687',
    messagingSenderId: '436153481478',
    projectId: 'r01-redditx-suicide',
    storageBucket: 'r01-redditx-suicide.firebasestorage.app',
    iosBundleId: 'com.dartmouth.smerb',
  );
}
